// Application constants and configuration

export const CARDS_FILE_PATH = process.env.CARDS_FILE_PATH || new URL('../data/cards.json', import.meta.url)

export const DECK_CONFIG = {
  mainDeck: {
    effectMonsters: 15,
    normalMonsters: 10,
    genericSpells: 10,
    genericTraps: 5,
  },
  extraDeck: {
    maxCards: 15,
  },
  maxCopiesPerCard: 3,
}

// Keywords that indicate a card is archetype-dependent
export const ARCHETYPE_DEPENDENT_KEYWORDS = [
  'Add 1 "',
  'Add a "',
  'Special Summon "',
  'Special summon "',
  'If you control a "',
  'If you control "',
  'target "...',
  '" monster',
  '" monster(s)',
  '" cards',
  'Equip only to "',
  'If your opponent controls',
  'Once per turn',
  'You can only use this effect of',
  'You can only activate 1',
  'per turn',
]

// Known archetype names and key terms to detect
export const KNOWN_ARCHETYPE_MARKERS = [
  'Blue-Eyes',
  'Black-Luster',
  'Dark Magician',
  'Magician',
  'HERO',
  'Elemental HERO',
  'Kashtira',
  'Branded',
  'Sky Striker',
  'Tearlaments',
  'Lavalval',
  'Linkuriboh',
  'Marincess',
  'Purrely',
  'Winda',
  'Ice Barrier',
  'Icejade',
  'Bystial',
  'Code Talker',
  'Crystal Beast',
  'Cyber Dragon',
  'Dark World',
  'Dinosaur',
  'D/D/D',
  'Dinosaur',
  'Equimax',
  'Flamvell',
  'Fossil',
  'Gadget',
  'Ghoiluster',
  'Gladiator Beast',
  'Granel',
  'Guardian',
  'Harpie',
  'Hellworld',
  'Ice Barrier',
  'Jurrac',
  'Krawler',
  'Laval',
  'Lyla',
  'Majestic',
  'Millennium',
  'Morphtronic',
  'Myutant',
  'Nemere',
  'Ojama',
  'Phantom',
  'Proton',
  'Pyrmoor',
  'Rikka',
  'Rock Kart',
  'Salvage',
  'Shaddoll',
  'Silkcity',
  'Sylvan',
  'Thunder Dragon',
  'Togex',
  'Tribe-Illusion',
  'U.A.',
  'Underworld',
  'Vylon',
  'Wabula',
  'Yami',
  'Zombie World',
]
